spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080